import {
  boolean,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
  index,
} from "drizzle-orm/pg-core";

export const queueStatusEnum = pgEnum("queue_status", [
  "WAITING",
  "ANSWERING",
  "ANSWERED",
  "CANCELLED",
  "DELETED",
  "SKIPPED",
  "PENDING_QUESTION",
  "PENDING_APPROVAL",
]);

export const queueTypeEnum = pgEnum("queue_type", ["NORMAL", "EXPRESS"]);

export const giftRules = pgTable(
  "gift_rules",
  {
    id: varchar("id", { length: 80 }).primaryKey(),
    giftCode: varchar("gift_code", { length: 80 }).notNull(),
    displayName: varchar("display_name", { length: 120 }).notNull(),
    icon: varchar("icon", { length: 24 }).notNull(),
    priority: integer("priority").notNull(),
    queueType: queueTypeEnum("queue_type").notNull().default("NORMAL"),
    questionLimit: integer("question_limit").notNull().default(1),
    unlimitedQuestions: boolean("unlimited_questions").notNull().default(false),
    multiplicationMode: varchar("multiplication_mode", { length: 16 }).notNull().default("MULTIPLY"),
    maxQuestions: integer("max_questions"),
    maximumQuestionsPerUser: integer("maximum_questions_per_user"),
    minimumGiftCount: integer("minimum_gift_count").notNull().default(1),
    isExpress: boolean("is_express").notNull().default(false),
    autoQueue: boolean("auto_queue").notNull().default(true),
    requireQuestion: boolean("require_question").notNull().default(true),
    active: boolean("active").notNull().default(true),
    colorTag: varchar("color_tag", { length: 16 }).notNull().default("DEFAULT"),
    displayOrder: integer("display_order").notNull().default(0),
    expressBehavior: varchar("express_behavior", { length: 32 }).notNull().default("BEFORE_NORMAL"),
    respectExistingExpressQueue: boolean("respect_existing_express_queue").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    giftCodeUnique: uniqueIndex("gift_rules_gift_code_uidx").on(table.giftCode),
    displayOrderIndex: index("gift_rules_display_order_idx").on(table.displayOrder),
  }),
);

export const queueSettings = pgTable("queue_settings", {
  id: varchar("id", { length: 64 }).primaryKey().default("default"),
  protectCurrentQuestion: boolean("protect_current_question").notNull().default(true),
  fifoSamePriority: boolean("fifo_same_priority").notNull().default(true),
  autoAdvance: boolean("auto_advance").notNull().default(false),
  skippedBehavior: varchar("skipped_behavior", { length: 32 }).notNull().default("SKIPPED_TAB"),
  duplicateQuestionMode: varchar("duplicate_question_mode", { length: 16 }).notNull().default("WARN"),
  upgradeExistingQueueOnExpress: boolean("upgrade_existing_queue_on_express").notNull().default(true),
  maxActiveQueues: integer("max_active_queues"),
  maxQuestionLength: integer("max_question_length"),
  pendingExpirationMinutes: integer("pending_expiration_minutes"),
  keepAnsweredHistory: boolean("keep_answered_history").notNull().default(true),
  confirmBeforeDelete: boolean("confirm_before_delete").notNull().default(true),
  showTikTokUsername: boolean("show_tiktok_username").notNull().default(true),
  showGiftName: boolean("show_gift_name").notNull().default(true),
  compactMode: boolean("compact_mode").notNull().default(false),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

/** A gift's unspent question allowance. One gift can fund several queue entries. */
export const questionCredits = pgTable(
  "question_credits",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: varchar("user_id", { length: 120 }),
    username: varchar("username", { length: 120 }).notNull(),
    displayName: varchar("display_name", { length: 120 }).notNull(),
    giftId: varchar("gift_id", { length: 80 }).notNull(),
    giftName: varchar("gift_name", { length: 120 }).notNull(),
    giftIcon: varchar("gift_icon", { length: 24 }).notNull(),
    priority: integer("priority").notNull(),
    queueType: queueTypeEnum("queue_type").notNull(),
    giftCount: integer("gift_count").notNull().default(1),
    initialQuestions: integer("initial_questions"),
    remainingQuestions: integer("remaining_questions"),
    ruleSnapshot: jsonb("rule_snapshot").$type<Record<string, unknown>>().notNull(),
    idempotencyKey: varchar("idempotency_key", { length: 180 }).notNull(),
    externalEventId: varchar("external_event_id", { length: 180 }),
    source: varchar("source", { length: 32 }).notNull().default("dashboard"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    idempotencyUnique: uniqueIndex("question_credits_idempotency_uidx").on(table.idempotencyKey),
    externalEventUnique: uniqueIndex("question_credits_external_event_uidx").on(table.externalEventId),
    usernameRemainingIndex: index("question_credits_username_remaining_idx").on(table.username, table.remainingQuestions, table.createdAt),
  }),
);

export const queueEntries = pgTable(
  "queue_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    queueNumber: serial("queue_number").notNull(),
    userId: varchar("user_id", { length: 120 }),
    username: varchar("username", { length: 120 }).notNull(),
    displayName: varchar("display_name", { length: 120 }).notNull(),
    question: text("question").notNull().default(""),
    giftId: varchar("gift_id", { length: 80 }).notNull(),
    giftName: varchar("gift_name", { length: 120 }).notNull(),
    giftIcon: varchar("gift_icon", { length: 24 }).notNull(),
    priority: integer("priority").notNull(),
    queueType: queueTypeEnum("queue_type").notNull(),
    giftCount: integer("gift_count").notNull().default(1),
    questionRights: integer("question_rights"),
    creditId: uuid("credit_id").references(() => questionCredits.id),
    ruleSnapshot: jsonb("rule_snapshot").$type<Record<string, unknown>>().notNull(),
    status: queueStatusEnum("status").notNull().default("WAITING"),
    pendingReason: varchar("pending_reason", { length: 240 }),
    idempotencyKey: varchar("idempotency_key", { length: 180 }).notNull(),
    externalEventId: varchar("external_event_id", { length: 180 }),
    dedupeKey: varchar("dedupe_key", { length: 600 }),
    source: varchar("source", { length: 32 }).notNull().default("dashboard"),
    queueEnteredAt: timestamp("queue_entered_at", { withTimezone: true }),
    movedToEnd: boolean("moved_to_end").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    answeredAt: timestamp("answered_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    idempotencyUnique: uniqueIndex("queue_entries_idempotency_uidx").on(table.idempotencyKey),
    externalEventUnique: uniqueIndex("queue_entries_external_event_uidx").on(table.externalEventId),
    dedupeUnique: uniqueIndex("queue_entries_active_dedupe_uidx").on(table.dedupeKey),
    statusCreatedIndex: index("queue_entries_status_created_idx").on(table.status, table.createdAt),
    orderingIndex: index("queue_entries_ordering_idx").on(table.status, table.priority, table.createdAt),
    priorityCreatedIndex: index("queue_entries_priority_created_idx").on(table.priority, table.createdAt),
    usernameStatusIndex: index("queue_entries_username_status_idx").on(table.username, table.status),
    creditIndex: index("queue_entries_credit_idx").on(table.creditId, table.createdAt),
  }),
);

export const queueEvents = pgTable(
  "queue_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    queueEntryId: uuid("queue_entry_id").notNull(),
    eventType: varchar("event_type", { length: 40 }).notNull(),
    fromStatus: queueStatusEnum("from_status"),
    toStatus: queueStatusEnum("to_status"),
    payload: jsonb("payload").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    queueEntryIndex: index("queue_events_queue_entry_idx").on(table.queueEntryId, table.createdAt),
  }),
);
